
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 45;
  public static final int STRING_LITERAL = 54;
  public static final int LBRACKET = 51;
  public static final int CHAR = 11;
  public static final int CHAR_LITERAL = 55;
  public static final int GE = 38;
  public static final int UMINUS = 56;
  public static final int PLUS_ASSIGN = 31;
  public static final int LPAREN = 49;
  public static final int SEMI = 7;
  public static final int CONTINUE = 29;
  public static final int INT = 4;
  public static final int MINUS = 43;
  public static final int FOR = 16;
  public static final int RPAREN = 50;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int LT = 35;
  public static final int READINTEGER = 25;
  public static final int CALLOUT = 28;
  public static final int OR = 40;
  public static final int COMMA = 47;
  public static final int CLASS = 2;
  public static final int NEWARRAY = 23;
  public static final int MULTIPLY = 44;
  public static final int PLUS = 42;
  public static final int ASSIGN = 30;
  public static final int IF = 18;
  public static final int THIS = 13;
  public static final int DOT = 48;
  public static final int ID = 3;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 20;
  public static final int RBRACKET = 52;
  public static final int TRUE = 26;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int NULL = 12;
  public static final int MOD = 46;
  public static final int NEQ = 34;
  public static final int BREAK = 21;
  public static final int VOID = 8;
  public static final int EQ = 33;
  public static final int LBRACE = 5;
  public static final int ELSE = 19;
  public static final int WHILE = 17;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 14;
  public static final int STRING = 10;
  public static final int FALSE = 27;
  public static final int GT = 37;
  public static final int IMPLEMENTS = 15;
  public static final int MINUS_ASSIGN = 32;
  public static final int PRINT = 24;
  public static final int INT_LITERAL = 53;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ID",
  "INT",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "VOID",
  "BOOLEAN",
  "STRING",
  "CHAR",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "TRUE",
  "FALSE",
  "CALLOUT",
  "CONTINUE",
  "ASSIGN",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "MOD",
  "COMMA",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "INT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "UMINUS"
  };
}

